# Example make.inc file for GCC
#
# NOTE: If compiling with GCC 10 or above append F90_OPTS, F77_OPTS and F90_DEBUGOPTS with:
#  -fallow-argument-mismatch
# See here for more details: https://gcc.gnu.org/gcc-10/porting_to.html

# Compiler, flags and preprocessing variables
F90 = ftn
F90_OPTS = -O3 -march=native -ffree-line-length-0 -fallow-argument-mismatch -fallow-invalid-boz 
CPP_ON_OPTS = -cpp -DXS -DISO -DLIBXC
F77 = $(F90)
F77_OPTS = -O3 -fallow-argument-mismatch -fallow-invalid-boz
# Required for compilation of LibXC 
FCCPP = cpp

F90_DEBUGOPTS = -g -O0 -DUSE_ASSERT -fbounds-check -fbacktrace -Wall -Wextra -ffree-line-length-0 -fcheck=all -finit-integer=2147483647 -finit-real=snan \
-frecord-gcc-switches -finit-character=42 -finit-logical=true -ffpe-trap=invalid,zero,overflow -fdump-core -fstack-protector-all -pipe -fallow-argument-mismatch -fallow-invalid-boz
# Unusable debug flags: -pedantic 
F77_DEBUGOPTS = $(F90_DEBUGOPTS)

# If compiling on mac, one may need to specify the location of the openMP header file.
# For example, if using Macports it may look like:
# INCL = -I/opt/local/lib/gcc10/gcc/x86_64-apple-darwin19/10.2.0/finclude/
INCL = 

# Libaries
# Use native blas/lapack by default
export USE_SYS_LAPACK=true
LIB_LPK = -L/opt/cray/pe/libsci/22.12.1.1/GNU/9.1/x86_64/lib/libsci_gnu_mpi_mp.a
LIB_FFT = fftlib.a
LIB_BZINT = libbzint.a
LIBS = $(LIB_LPK) $(LIB_FFT) $(LIB_BZINT)

# SMP and MPI compilers, flags and preprocessing variables
MPIF90 = ftn
MPIF90_OPTS = -DMPI -D_HDF5_
MPI_LIBS = -I/opt/cray/pe/hdf5-parallel/1.12.2.1/include -Wl,-rpath -Wl,/opt/cray/pe/hdf5-parallel/1.12.2.1/gnu/9.1/lib

# To use Scalapack, include the preprocessing variable, provide the library path and library name 
#MPIF90_OPTS = -DMPI -DSCAL
#MPI_LIBS = -L/opt/local/lib/ -lscalapack

SMPF90_OPTS = -fopenmp -DUSEOMP
SMPF77_OPTS = $(SMPF90_OPTS)
SMP_LIBS = 

BUILDMPI = true
BUILDSMP = true
BUILDMPISMP = true
